## This is the begining of something really beautiful.

In [ ]:
print("Hello, I am learning all the good things in Pytorch")

Hello, I am learning all the good things in Pytorch


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Intoduction to tensors

In [ ]:
# Scaler Tensor
scaler = torch.tensor(7) #
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item() # getting tensor back as python int

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
test = torch.tensor([[[[1,2]]],[[[1,2]]]])

In [ ]:
test.shape

torch.Size([2, 1, 1, 2])

## Random Tensors : a multidimensional array where each element is filled with a random number

### Why is random Tensor important
How neural network works is
- Starts with a random numbers
- Looks at the data
- Updares the random numbers
- Looks at the data
- Updates the random numbers

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.7835, 0.8230, 0.2028, 0.1052],
        [0.0674, 0.3023, 0.2456, 0.4564],
        [0.1743, 0.4011, 0.2795, 0.4679]])

## Create a random tensor with simialr shape to an image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zero and One Tensors

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Range and tensors-like

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Tensor like: when you wanna make a simialar tensor without specifying the shape of a tensor.
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatype

### Precision: By default it is 32
  - Single precsion : 32 bit -  for normal
  - Double Precision : 64 bit - for more accuracy
  - Half Precison : 16 bit - Speeding up the calculation

Note : Tensor datatypes error is the most run into error:
  1. Not right datatype
  2. Not right shape
  3. Not right device

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, # what device is your tensor on eg: "cuda"
                               requires_grad=False ) # should track the gradient or not
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Convert the float32 to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
multiplying_tensor = float_16_tensor * float_32_tensor
multiplying_tensor.dtype

torch.float32

In [ ]:
Some_32_tensor = torch.tensor([3,6,9], dtype=torch.float32, device='cpu')
Some_32_tensor

tensor([3., 6., 9.])

In [ ]:
## Why is torch.matmul way faster?

## Adjust shape of tensor

In [ ]:
tensor_A = torch.tensor([[3,2],[4,5],[6,7]])
tensor_B = torch.tensor([[1,2],[3,4],[5,6]])


In [ ]:
# Can't do this multiplication because the shape doesnt match for matrix multiplication torch.matmul(tensor_A, tensor_B)

# Solution: Transpose
tensor_B = tensor_B.T

In [ ]:
torch.matmul(tensor_A, tensor_B)

tensor([[ 7, 17, 27],
        [14, 32, 50],
        [20, 46, 72]])

## Tensor aggregation

In [ ]:
x=torch.arange(0,10)
x, x.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [ ]:
x.min(), x.max(), x.type(torch.float32).mean() ## You needed to change the type of x because by default arange creates long int, and mean can't work on long int.

(tensor(0), tensor(9), tensor(4.5000))

In [ ]:
torch.sum(x)

tensor(45)

 ## Reshaping , view, stack, sqeeuze
 1. Reshapes an input tensor to a defined shape
 2. View returns a view of an input tensor of certain shape but keep the same memory as the original tensor
 3. Stacking combines multiple tensors on top of each other (vstack) or side by side (hstack)
 4. Squeeze removes all '1' dimensions from a tensor
 5. Unsqueeze adds a '1' dimension to a target tensor
 6. Permute returns a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
x_reshaped = x.reshape(2,5)
x_reshaped

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Squeeze
x_squeezed = torch.squeeze(x)
x_squeezed

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 ## Numpy to pytorch


In [ ]:
import numpy as np
import torch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
# The defualt type of numpy is float64, whearas that of pytorch is float32
# While converting the numpy to tensor it will be of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Random Seed : removing the randomness from random.

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
random_tensor_C
## Reporducability

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## Running tensors and Pytorch object on GPU

In [ ]:
!nvidia-smi

Wed Jan 15 16:08:29 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P0              25W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:

import torch

# Check for GPU availability
if torch.cuda.is_available():
  print("GPU is available")
  device = torch.device("cuda")
else:
  print("GPU is not available, using CPU instead")
  device = torch.device("cpu")

# Example tensor on the selected device
tensor = torch.rand(3,4).to(device)
tensor

GPU is available


tensor([[0.3427, 0.5646, 0.6860, 0.4560],
        [0.9532, 0.2149, 0.2398, 0.8521],
        [0.2301, 0.9590, 0.1731, 0.2373]], device='cuda:0')