## This is the begining of something really beautiful.

In [ ]:
print("Hello, I am learning all the good things in Pytorch")

Hello, I am learning all the good things in Pytorch


In [ ]:
!nvidia-smi

Mon Jan 13 02:27:18 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Intoduction to tensors

In [2]:
# Scaler Tensor
scaler = torch.tensor(7) #
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item() # getting tensor back as python int

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [22]:
test = torch.tensor([[[[1,2]]],[[[1,2]]]])

In [23]:
test.shape

torch.Size([2, 1, 1, 2])

## Random Tensors : a multidimensional array where each element is filled with a random number

### Why is random Tensor important
How neural network works is
- Starts with a random numbers
- Looks at the data
- Updares the random numbers
- Looks at the data
- Updates the random numbers

In [24]:
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.7835, 0.8230, 0.2028, 0.1052],
        [0.0674, 0.3023, 0.2456, 0.4564],
        [0.1743, 0.4011, 0.2795, 0.4679]])

## Create a random tensor with simialr shape to an image tensor

In [26]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zero and One Tensors

In [28]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

## Range and tensors-like

In [35]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Tensor like: when you wanna make a simialar tensor without specifying the shape of a tensor.
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatype

### Precision: By default it is 32
  - Single precsion : 32 bit -  for normal
  - Double Precision : 64 bit - for more accuracy
  - Half Precison : 16 bit - Speeding up the calculation

Note : Tensor datatypes error is the most run into error:
  1. Not right datatype
  2. Not right shape
  3. Not right device

In [37]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, # what device is your tensor on eg: "cuda"
                               requires_grad=False ) # should track the gradient or not
float_32_tensor

tensor([3., 6., 9.])

In [38]:
# Convert the float32 to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
multiplying_tensor = float_16_tensor * float_32_tensor
multiplying_tensor.dtype

torch.float32